// This file is generated by Slice Machine. Update with care!

import Projeto01 from './Projeto01';
import Projeto02 from './Projeto02';
import Projeto04 from './Projeto04';

export {
	Projeto01,
	Projeto02,
	Projeto04,
};

export const components = {
	projeto01: Projeto01,
	projeto02: Projeto02,
	projeto04: Projeto04,
};
